language: node_js
node_js:
  - '8'
before_install:
  - npm install -g ganache-cli
before_script:
  - ganache-cli > /dev/null &
script:
  - npm run lint
  - npm run solhint
  - npm run test
  - ./node_modules/.bin/solidity-coverage && cat ./coverage/lcov.info | coveralls
